name: Python FOREX library tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test forex library with pytest
        run: |
          export PYTHONPATH=$PWD
          export TOKEN=${{ secrets.OANDA_TOKEN  }}
          pip install pytest && cd tests/forex/
          pytest -s -v
      - name: Test forex library with pytest
        run: |
          export PYTHONPATH=$PWD
          export TOKEN=${{ secrets.OANDA_TOKEN  }}
          pip install pytest && cd tests/api/
          pytest -s -v
